// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_FB_SENSOR_MSGS_H_
#define FLATBUFFERS_GENERATED_SCHEMA_FB_SENSOR_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace fb {

struct MsgMetadata;
struct MsgMetadataBuilder;
struct MsgMetadataT;

struct MsgWithMetadata;
struct MsgWithMetadataBuilder;
struct MsgWithMetadataT;

struct RosTime;

struct RosDuration;

namespace std_msgs {

struct Header;
struct HeaderBuilder;
struct HeaderT;

}  // namespace std_msgs

namespace sensor_msgs {

struct NavSatStatusConstants;
struct NavSatStatusConstantsBuilder;
struct NavSatStatusConstantsT;

struct NavSatStatus;
struct NavSatStatusBuilder;
struct NavSatStatusT;

struct NavSatFixConstants;
struct NavSatFixConstantsBuilder;
struct NavSatFixConstantsT;

struct NavSatFix;
struct NavSatFixBuilder;
struct NavSatFixT;

}  // namespace sensor_msgs

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RosTime FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t secs_;
  uint32_t nsecs_;

 public:
  RosTime() {
    memset(static_cast<void *>(this), 0, sizeof(RosTime));
  }
  RosTime(uint32_t _secs, uint32_t _nsecs)
      : secs_(flatbuffers::EndianScalar(_secs)),
        nsecs_(flatbuffers::EndianScalar(_nsecs)) {
  }
  uint32_t secs() const {
    return flatbuffers::EndianScalar(secs_);
  }
  uint32_t nsecs() const {
    return flatbuffers::EndianScalar(nsecs_);
  }
};
FLATBUFFERS_STRUCT_END(RosTime, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) RosDuration FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t secs_;
  int32_t nsecs_;

 public:
  RosDuration() {
    memset(static_cast<void *>(this), 0, sizeof(RosDuration));
  }
  RosDuration(int32_t _secs, int32_t _nsecs)
      : secs_(flatbuffers::EndianScalar(_secs)),
        nsecs_(flatbuffers::EndianScalar(_nsecs)) {
  }
  int32_t secs() const {
    return flatbuffers::EndianScalar(secs_);
  }
  int32_t nsecs() const {
    return flatbuffers::EndianScalar(nsecs_);
  }
};
FLATBUFFERS_STRUCT_END(RosDuration, 8);

struct MsgMetadataT : public flatbuffers::NativeTable {
  typedef MsgMetadata TableType;
  std::string topic;
  MsgMetadataT() {
  }
};

struct MsgMetadata FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MsgMetadataT NativeTableType;
  typedef MsgMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOPIC = 4
  };
  const flatbuffers::String *topic() const {
    return GetPointer<const flatbuffers::String *>(VT_TOPIC);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TOPIC) &&
           verifier.VerifyString(topic()) &&
           verifier.EndTable();
  }
  MsgMetadataT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MsgMetadataT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<MsgMetadata> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MsgMetadataT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MsgMetadataBuilder {
  typedef MsgMetadata Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_topic(flatbuffers::Offset<flatbuffers::String> topic) {
    fbb_.AddOffset(MsgMetadata::VT_TOPIC, topic);
  }
  explicit MsgMetadataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgMetadataBuilder &operator=(const MsgMetadataBuilder &);
  flatbuffers::Offset<MsgMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MsgMetadata>(end);
    return o;
  }
};

inline flatbuffers::Offset<MsgMetadata> CreateMsgMetadata(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> topic = 0) {
  MsgMetadataBuilder builder_(_fbb);
  builder_.add_topic(topic);
  return builder_.Finish();
}

inline flatbuffers::Offset<MsgMetadata> CreateMsgMetadataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *topic = nullptr) {
  auto topic__ = topic ? _fbb.CreateString(topic) : 0;
  return fb::CreateMsgMetadata(
      _fbb,
      topic__);
}

flatbuffers::Offset<MsgMetadata> CreateMsgMetadata(flatbuffers::FlatBufferBuilder &_fbb, const MsgMetadataT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MsgWithMetadataT : public flatbuffers::NativeTable {
  typedef MsgWithMetadata TableType;
  std::unique_ptr<fb::MsgMetadataT> __metadata;
  MsgWithMetadataT() {
  }
};

struct MsgWithMetadata FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MsgWithMetadataT NativeTableType;
  typedef MsgWithMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT___METADATA = 4
  };
  const fb::MsgMetadata *__metadata() const {
    return GetPointer<const fb::MsgMetadata *>(VT___METADATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT___METADATA) &&
           verifier.VerifyTable(__metadata()) &&
           verifier.EndTable();
  }
  MsgWithMetadataT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MsgWithMetadataT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<MsgWithMetadata> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MsgWithMetadataT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct MsgWithMetadataBuilder {
  typedef MsgWithMetadata Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add___metadata(flatbuffers::Offset<fb::MsgMetadata> __metadata) {
    fbb_.AddOffset(MsgWithMetadata::VT___METADATA, __metadata);
  }
  explicit MsgWithMetadataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MsgWithMetadataBuilder &operator=(const MsgWithMetadataBuilder &);
  flatbuffers::Offset<MsgWithMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<MsgWithMetadata>(end);
    return o;
  }
};

inline flatbuffers::Offset<MsgWithMetadata> CreateMsgWithMetadata(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0) {
  MsgWithMetadataBuilder builder_(_fbb);
  builder_.add___metadata(__metadata);
  return builder_.Finish();
}

flatbuffers::Offset<MsgWithMetadata> CreateMsgWithMetadata(flatbuffers::FlatBufferBuilder &_fbb, const MsgWithMetadataT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

namespace std_msgs {

struct HeaderT : public flatbuffers::NativeTable {
  typedef Header TableType;
  std::unique_ptr<fb::MsgMetadataT> __metadata;
  uint32_t seq;
  std::unique_ptr<fb::RosTime> stamp;
  std::string frame_id;
  HeaderT()
      : seq(0) {
  }
};

struct Header FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef HeaderT NativeTableType;
  typedef HeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT___METADATA = 4,
    VT_SEQ = 6,
    VT_STAMP = 8,
    VT_FRAME_ID = 10
  };
  const fb::MsgMetadata *__metadata() const {
    return GetPointer<const fb::MsgMetadata *>(VT___METADATA);
  }
  uint32_t seq() const {
    return GetField<uint32_t>(VT_SEQ, 0);
  }
  const fb::RosTime *stamp() const {
    return GetStruct<const fb::RosTime *>(VT_STAMP);
  }
  const flatbuffers::String *frame_id() const {
    return GetPointer<const flatbuffers::String *>(VT_FRAME_ID);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT___METADATA) &&
           verifier.VerifyTable(__metadata()) &&
           VerifyField<uint32_t>(verifier, VT_SEQ) &&
           VerifyField<fb::RosTime>(verifier, VT_STAMP) &&
           VerifyOffset(verifier, VT_FRAME_ID) &&
           verifier.VerifyString(frame_id()) &&
           verifier.EndTable();
  }
  HeaderT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(HeaderT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Header> Pack(flatbuffers::FlatBufferBuilder &_fbb, const HeaderT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct HeaderBuilder {
  typedef Header Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add___metadata(flatbuffers::Offset<fb::MsgMetadata> __metadata) {
    fbb_.AddOffset(Header::VT___METADATA, __metadata);
  }
  void add_seq(uint32_t seq) {
    fbb_.AddElement<uint32_t>(Header::VT_SEQ, seq, 0);
  }
  void add_stamp(const fb::RosTime *stamp) {
    fbb_.AddStruct(Header::VT_STAMP, stamp);
  }
  void add_frame_id(flatbuffers::Offset<flatbuffers::String> frame_id) {
    fbb_.AddOffset(Header::VT_FRAME_ID, frame_id);
  }
  explicit HeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  HeaderBuilder &operator=(const HeaderBuilder &);
  flatbuffers::Offset<Header> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Header>(end);
    return o;
  }
};

inline flatbuffers::Offset<Header> CreateHeader(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0,
    uint32_t seq = 0,
    const fb::RosTime *stamp = 0,
    flatbuffers::Offset<flatbuffers::String> frame_id = 0) {
  HeaderBuilder builder_(_fbb);
  builder_.add_frame_id(frame_id);
  builder_.add_stamp(stamp);
  builder_.add_seq(seq);
  builder_.add___metadata(__metadata);
  return builder_.Finish();
}

inline flatbuffers::Offset<Header> CreateHeaderDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0,
    uint32_t seq = 0,
    const fb::RosTime *stamp = 0,
    const char *frame_id = nullptr) {
  auto frame_id__ = frame_id ? _fbb.CreateString(frame_id) : 0;
  return fb::std_msgs::CreateHeader(
      _fbb,
      __metadata,
      seq,
      stamp,
      frame_id__);
}

flatbuffers::Offset<Header> CreateHeader(flatbuffers::FlatBufferBuilder &_fbb, const HeaderT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace std_msgs

namespace sensor_msgs {

struct NavSatStatusConstantsT : public flatbuffers::NativeTable {
  typedef NavSatStatusConstants TableType;
  int8_t status_no_fix;
  int8_t status_fix;
  int8_t status_sbas_fix;
  int8_t status_gbas_fix;
  uint16_t service_gps;
  uint16_t service_glonass;
  uint16_t service_compass;
  uint16_t service_galileo;
  NavSatStatusConstantsT()
      : status_no_fix(-1),
        status_fix(0),
        status_sbas_fix(1),
        status_gbas_fix(2),
        service_gps(1),
        service_glonass(2),
        service_compass(4),
        service_galileo(8) {
  }
};

struct NavSatStatusConstants FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef NavSatStatusConstantsT NativeTableType;
  typedef NavSatStatusConstantsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STATUS_NO_FIX = 4,
    VT_STATUS_FIX = 6,
    VT_STATUS_SBAS_FIX = 8,
    VT_STATUS_GBAS_FIX = 10,
    VT_SERVICE_GPS = 12,
    VT_SERVICE_GLONASS = 14,
    VT_SERVICE_COMPASS = 16,
    VT_SERVICE_GALILEO = 18
  };
  int8_t status_no_fix() const {
    return GetField<int8_t>(VT_STATUS_NO_FIX, -1);
  }
  int8_t status_fix() const {
    return GetField<int8_t>(VT_STATUS_FIX, 0);
  }
  int8_t status_sbas_fix() const {
    return GetField<int8_t>(VT_STATUS_SBAS_FIX, 1);
  }
  int8_t status_gbas_fix() const {
    return GetField<int8_t>(VT_STATUS_GBAS_FIX, 2);
  }
  uint16_t service_gps() const {
    return GetField<uint16_t>(VT_SERVICE_GPS, 1);
  }
  uint16_t service_glonass() const {
    return GetField<uint16_t>(VT_SERVICE_GLONASS, 2);
  }
  uint16_t service_compass() const {
    return GetField<uint16_t>(VT_SERVICE_COMPASS, 4);
  }
  uint16_t service_galileo() const {
    return GetField<uint16_t>(VT_SERVICE_GALILEO, 8);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_STATUS_NO_FIX) &&
           VerifyField<int8_t>(verifier, VT_STATUS_FIX) &&
           VerifyField<int8_t>(verifier, VT_STATUS_SBAS_FIX) &&
           VerifyField<int8_t>(verifier, VT_STATUS_GBAS_FIX) &&
           VerifyField<uint16_t>(verifier, VT_SERVICE_GPS) &&
           VerifyField<uint16_t>(verifier, VT_SERVICE_GLONASS) &&
           VerifyField<uint16_t>(verifier, VT_SERVICE_COMPASS) &&
           VerifyField<uint16_t>(verifier, VT_SERVICE_GALILEO) &&
           verifier.EndTable();
  }
  NavSatStatusConstantsT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NavSatStatusConstantsT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<NavSatStatusConstants> Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusConstantsT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NavSatStatusConstantsBuilder {
  typedef NavSatStatusConstants Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_status_no_fix(int8_t status_no_fix) {
    fbb_.AddElement<int8_t>(NavSatStatusConstants::VT_STATUS_NO_FIX, status_no_fix, -1);
  }
  void add_status_fix(int8_t status_fix) {
    fbb_.AddElement<int8_t>(NavSatStatusConstants::VT_STATUS_FIX, status_fix, 0);
  }
  void add_status_sbas_fix(int8_t status_sbas_fix) {
    fbb_.AddElement<int8_t>(NavSatStatusConstants::VT_STATUS_SBAS_FIX, status_sbas_fix, 1);
  }
  void add_status_gbas_fix(int8_t status_gbas_fix) {
    fbb_.AddElement<int8_t>(NavSatStatusConstants::VT_STATUS_GBAS_FIX, status_gbas_fix, 2);
  }
  void add_service_gps(uint16_t service_gps) {
    fbb_.AddElement<uint16_t>(NavSatStatusConstants::VT_SERVICE_GPS, service_gps, 1);
  }
  void add_service_glonass(uint16_t service_glonass) {
    fbb_.AddElement<uint16_t>(NavSatStatusConstants::VT_SERVICE_GLONASS, service_glonass, 2);
  }
  void add_service_compass(uint16_t service_compass) {
    fbb_.AddElement<uint16_t>(NavSatStatusConstants::VT_SERVICE_COMPASS, service_compass, 4);
  }
  void add_service_galileo(uint16_t service_galileo) {
    fbb_.AddElement<uint16_t>(NavSatStatusConstants::VT_SERVICE_GALILEO, service_galileo, 8);
  }
  explicit NavSatStatusConstantsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NavSatStatusConstantsBuilder &operator=(const NavSatStatusConstantsBuilder &);
  flatbuffers::Offset<NavSatStatusConstants> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<NavSatStatusConstants>(end);
    return o;
  }
};

inline flatbuffers::Offset<NavSatStatusConstants> CreateNavSatStatusConstants(
    flatbuffers::FlatBufferBuilder &_fbb,
    int8_t status_no_fix = -1,
    int8_t status_fix = 0,
    int8_t status_sbas_fix = 1,
    int8_t status_gbas_fix = 2,
    uint16_t service_gps = 1,
    uint16_t service_glonass = 2,
    uint16_t service_compass = 4,
    uint16_t service_galileo = 8) {
  NavSatStatusConstantsBuilder builder_(_fbb);
  builder_.add_service_galileo(service_galileo);
  builder_.add_service_compass(service_compass);
  builder_.add_service_glonass(service_glonass);
  builder_.add_service_gps(service_gps);
  builder_.add_status_gbas_fix(status_gbas_fix);
  builder_.add_status_sbas_fix(status_sbas_fix);
  builder_.add_status_fix(status_fix);
  builder_.add_status_no_fix(status_no_fix);
  return builder_.Finish();
}

flatbuffers::Offset<NavSatStatusConstants> CreateNavSatStatusConstants(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusConstantsT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NavSatStatusT : public flatbuffers::NativeTable {
  typedef NavSatStatus TableType;
  std::unique_ptr<fb::MsgMetadataT> __metadata;
  int8_t status;
  uint16_t service;
  NavSatStatusT()
      : status(0),
        service(0) {
  }
};

struct NavSatStatus FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef NavSatStatusT NativeTableType;
  typedef NavSatStatusBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT___METADATA = 4,
    VT_STATUS = 6,
    VT_SERVICE = 8
  };
  const fb::MsgMetadata *__metadata() const {
    return GetPointer<const fb::MsgMetadata *>(VT___METADATA);
  }
  int8_t status() const {
    return GetField<int8_t>(VT_STATUS, 0);
  }
  uint16_t service() const {
    return GetField<uint16_t>(VT_SERVICE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT___METADATA) &&
           verifier.VerifyTable(__metadata()) &&
           VerifyField<int8_t>(verifier, VT_STATUS) &&
           VerifyField<uint16_t>(verifier, VT_SERVICE) &&
           verifier.EndTable();
  }
  NavSatStatusT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NavSatStatusT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<NavSatStatus> Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NavSatStatusBuilder {
  typedef NavSatStatus Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add___metadata(flatbuffers::Offset<fb::MsgMetadata> __metadata) {
    fbb_.AddOffset(NavSatStatus::VT___METADATA, __metadata);
  }
  void add_status(int8_t status) {
    fbb_.AddElement<int8_t>(NavSatStatus::VT_STATUS, status, 0);
  }
  void add_service(uint16_t service) {
    fbb_.AddElement<uint16_t>(NavSatStatus::VT_SERVICE, service, 0);
  }
  explicit NavSatStatusBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NavSatStatusBuilder &operator=(const NavSatStatusBuilder &);
  flatbuffers::Offset<NavSatStatus> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<NavSatStatus>(end);
    return o;
  }
};

inline flatbuffers::Offset<NavSatStatus> CreateNavSatStatus(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0,
    int8_t status = 0,
    uint16_t service = 0) {
  NavSatStatusBuilder builder_(_fbb);
  builder_.add___metadata(__metadata);
  builder_.add_service(service);
  builder_.add_status(status);
  return builder_.Finish();
}

flatbuffers::Offset<NavSatStatus> CreateNavSatStatus(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NavSatFixConstantsT : public flatbuffers::NativeTable {
  typedef NavSatFixConstants TableType;
  uint8_t covariance_type_unknown;
  uint8_t covariance_type_approximated;
  uint8_t covariance_type_diagonal_known;
  uint8_t covariance_type_known;
  NavSatFixConstantsT()
      : covariance_type_unknown(0),
        covariance_type_approximated(1),
        covariance_type_diagonal_known(2),
        covariance_type_known(3) {
  }
};

struct NavSatFixConstants FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef NavSatFixConstantsT NativeTableType;
  typedef NavSatFixConstantsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COVARIANCE_TYPE_UNKNOWN = 4,
    VT_COVARIANCE_TYPE_APPROXIMATED = 6,
    VT_COVARIANCE_TYPE_DIAGONAL_KNOWN = 8,
    VT_COVARIANCE_TYPE_KNOWN = 10
  };
  uint8_t covariance_type_unknown() const {
    return GetField<uint8_t>(VT_COVARIANCE_TYPE_UNKNOWN, 0);
  }
  uint8_t covariance_type_approximated() const {
    return GetField<uint8_t>(VT_COVARIANCE_TYPE_APPROXIMATED, 1);
  }
  uint8_t covariance_type_diagonal_known() const {
    return GetField<uint8_t>(VT_COVARIANCE_TYPE_DIAGONAL_KNOWN, 2);
  }
  uint8_t covariance_type_known() const {
    return GetField<uint8_t>(VT_COVARIANCE_TYPE_KNOWN, 3);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_COVARIANCE_TYPE_UNKNOWN) &&
           VerifyField<uint8_t>(verifier, VT_COVARIANCE_TYPE_APPROXIMATED) &&
           VerifyField<uint8_t>(verifier, VT_COVARIANCE_TYPE_DIAGONAL_KNOWN) &&
           VerifyField<uint8_t>(verifier, VT_COVARIANCE_TYPE_KNOWN) &&
           verifier.EndTable();
  }
  NavSatFixConstantsT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NavSatFixConstantsT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<NavSatFixConstants> Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixConstantsT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NavSatFixConstantsBuilder {
  typedef NavSatFixConstants Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_covariance_type_unknown(uint8_t covariance_type_unknown) {
    fbb_.AddElement<uint8_t>(NavSatFixConstants::VT_COVARIANCE_TYPE_UNKNOWN, covariance_type_unknown, 0);
  }
  void add_covariance_type_approximated(uint8_t covariance_type_approximated) {
    fbb_.AddElement<uint8_t>(NavSatFixConstants::VT_COVARIANCE_TYPE_APPROXIMATED, covariance_type_approximated, 1);
  }
  void add_covariance_type_diagonal_known(uint8_t covariance_type_diagonal_known) {
    fbb_.AddElement<uint8_t>(NavSatFixConstants::VT_COVARIANCE_TYPE_DIAGONAL_KNOWN, covariance_type_diagonal_known, 2);
  }
  void add_covariance_type_known(uint8_t covariance_type_known) {
    fbb_.AddElement<uint8_t>(NavSatFixConstants::VT_COVARIANCE_TYPE_KNOWN, covariance_type_known, 3);
  }
  explicit NavSatFixConstantsBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NavSatFixConstantsBuilder &operator=(const NavSatFixConstantsBuilder &);
  flatbuffers::Offset<NavSatFixConstants> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<NavSatFixConstants>(end);
    return o;
  }
};

inline flatbuffers::Offset<NavSatFixConstants> CreateNavSatFixConstants(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t covariance_type_unknown = 0,
    uint8_t covariance_type_approximated = 1,
    uint8_t covariance_type_diagonal_known = 2,
    uint8_t covariance_type_known = 3) {
  NavSatFixConstantsBuilder builder_(_fbb);
  builder_.add_covariance_type_known(covariance_type_known);
  builder_.add_covariance_type_diagonal_known(covariance_type_diagonal_known);
  builder_.add_covariance_type_approximated(covariance_type_approximated);
  builder_.add_covariance_type_unknown(covariance_type_unknown);
  return builder_.Finish();
}

flatbuffers::Offset<NavSatFixConstants> CreateNavSatFixConstants(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixConstantsT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NavSatFixT : public flatbuffers::NativeTable {
  typedef NavSatFix TableType;
  std::unique_ptr<fb::MsgMetadataT> __metadata;
  std::unique_ptr<fb::std_msgs::HeaderT> header;
  std::unique_ptr<fb::sensor_msgs::NavSatStatusT> status;
  double latitude;
  double longitude;
  double altitude;
  std::vector<double> position_covariance;
  uint8_t position_covariance_type;
  NavSatFixT()
      : latitude(0.0),
        longitude(0.0),
        altitude(0.0),
        position_covariance_type(0) {
  }
};

struct NavSatFix FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef NavSatFixT NativeTableType;
  typedef NavSatFixBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT___METADATA = 4,
    VT_HEADER = 6,
    VT_STATUS = 8,
    VT_LATITUDE = 10,
    VT_LONGITUDE = 12,
    VT_ALTITUDE = 14,
    VT_POSITION_COVARIANCE = 16,
    VT_POSITION_COVARIANCE_TYPE = 18
  };
  const fb::MsgMetadata *__metadata() const {
    return GetPointer<const fb::MsgMetadata *>(VT___METADATA);
  }
  const fb::std_msgs::Header *header() const {
    return GetPointer<const fb::std_msgs::Header *>(VT_HEADER);
  }
  const fb::sensor_msgs::NavSatStatus *status() const {
    return GetPointer<const fb::sensor_msgs::NavSatStatus *>(VT_STATUS);
  }
  double latitude() const {
    return GetField<double>(VT_LATITUDE, 0.0);
  }
  double longitude() const {
    return GetField<double>(VT_LONGITUDE, 0.0);
  }
  double altitude() const {
    return GetField<double>(VT_ALTITUDE, 0.0);
  }
  const flatbuffers::Vector<double> *position_covariance() const {
    return GetPointer<const flatbuffers::Vector<double> *>(VT_POSITION_COVARIANCE);
  }
  uint8_t position_covariance_type() const {
    return GetField<uint8_t>(VT_POSITION_COVARIANCE_TYPE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT___METADATA) &&
           verifier.VerifyTable(__metadata()) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyOffset(verifier, VT_STATUS) &&
           verifier.VerifyTable(status()) &&
           VerifyField<double>(verifier, VT_LATITUDE) &&
           VerifyField<double>(verifier, VT_LONGITUDE) &&
           VerifyField<double>(verifier, VT_ALTITUDE) &&
           VerifyOffset(verifier, VT_POSITION_COVARIANCE) &&
           verifier.VerifyVector(position_covariance()) &&
           VerifyField<uint8_t>(verifier, VT_POSITION_COVARIANCE_TYPE) &&
           verifier.EndTable();
  }
  NavSatFixT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NavSatFixT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<NavSatFix> Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NavSatFixBuilder {
  typedef NavSatFix Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add___metadata(flatbuffers::Offset<fb::MsgMetadata> __metadata) {
    fbb_.AddOffset(NavSatFix::VT___METADATA, __metadata);
  }
  void add_header(flatbuffers::Offset<fb::std_msgs::Header> header) {
    fbb_.AddOffset(NavSatFix::VT_HEADER, header);
  }
  void add_status(flatbuffers::Offset<fb::sensor_msgs::NavSatStatus> status) {
    fbb_.AddOffset(NavSatFix::VT_STATUS, status);
  }
  void add_latitude(double latitude) {
    fbb_.AddElement<double>(NavSatFix::VT_LATITUDE, latitude, 0.0);
  }
  void add_longitude(double longitude) {
    fbb_.AddElement<double>(NavSatFix::VT_LONGITUDE, longitude, 0.0);
  }
  void add_altitude(double altitude) {
    fbb_.AddElement<double>(NavSatFix::VT_ALTITUDE, altitude, 0.0);
  }
  void add_position_covariance(flatbuffers::Offset<flatbuffers::Vector<double>> position_covariance) {
    fbb_.AddOffset(NavSatFix::VT_POSITION_COVARIANCE, position_covariance);
  }
  void add_position_covariance_type(uint8_t position_covariance_type) {
    fbb_.AddElement<uint8_t>(NavSatFix::VT_POSITION_COVARIANCE_TYPE, position_covariance_type, 0);
  }
  explicit NavSatFixBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  NavSatFixBuilder &operator=(const NavSatFixBuilder &);
  flatbuffers::Offset<NavSatFix> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<NavSatFix>(end);
    return o;
  }
};

inline flatbuffers::Offset<NavSatFix> CreateNavSatFix(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0,
    flatbuffers::Offset<fb::std_msgs::Header> header = 0,
    flatbuffers::Offset<fb::sensor_msgs::NavSatStatus> status = 0,
    double latitude = 0.0,
    double longitude = 0.0,
    double altitude = 0.0,
    flatbuffers::Offset<flatbuffers::Vector<double>> position_covariance = 0,
    uint8_t position_covariance_type = 0) {
  NavSatFixBuilder builder_(_fbb);
  builder_.add_altitude(altitude);
  builder_.add_longitude(longitude);
  builder_.add_latitude(latitude);
  builder_.add_position_covariance(position_covariance);
  builder_.add_status(status);
  builder_.add_header(header);
  builder_.add___metadata(__metadata);
  builder_.add_position_covariance_type(position_covariance_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<NavSatFix> CreateNavSatFixDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<fb::MsgMetadata> __metadata = 0,
    flatbuffers::Offset<fb::std_msgs::Header> header = 0,
    flatbuffers::Offset<fb::sensor_msgs::NavSatStatus> status = 0,
    double latitude = 0.0,
    double longitude = 0.0,
    double altitude = 0.0,
    const std::vector<double> *position_covariance = nullptr,
    uint8_t position_covariance_type = 0) {
  auto position_covariance__ = position_covariance ? _fbb.CreateVector<double>(*position_covariance) : 0;
  return fb::sensor_msgs::CreateNavSatFix(
      _fbb,
      __metadata,
      header,
      status,
      latitude,
      longitude,
      altitude,
      position_covariance__,
      position_covariance_type);
}

flatbuffers::Offset<NavSatFix> CreateNavSatFix(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

}  // namespace sensor_msgs

inline MsgMetadataT *MsgMetadata::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::MsgMetadataT> _o = std::unique_ptr<fb::MsgMetadataT>(new MsgMetadataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MsgMetadata::UnPackTo(MsgMetadataT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = topic(); if (_e) _o->topic = _e->str(); }
}

inline flatbuffers::Offset<MsgMetadata> MsgMetadata::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MsgMetadataT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMsgMetadata(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<MsgMetadata> CreateMsgMetadata(flatbuffers::FlatBufferBuilder &_fbb, const MsgMetadataT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MsgMetadataT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _topic = _o->topic.empty() ? 0 : _fbb.CreateString(_o->topic);
  return fb::CreateMsgMetadata(
      _fbb,
      _topic);
}

inline MsgWithMetadataT *MsgWithMetadata::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::MsgWithMetadataT> _o = std::unique_ptr<fb::MsgWithMetadataT>(new MsgWithMetadataT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MsgWithMetadata::UnPackTo(MsgWithMetadataT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = __metadata(); if (_e) _o->__metadata = std::unique_ptr<fb::MsgMetadataT>(_e->UnPack(_resolver)); }
}

inline flatbuffers::Offset<MsgWithMetadata> MsgWithMetadata::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MsgWithMetadataT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMsgWithMetadata(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<MsgWithMetadata> CreateMsgWithMetadata(flatbuffers::FlatBufferBuilder &_fbb, const MsgWithMetadataT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MsgWithMetadataT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto ___metadata = _o->__metadata ? CreateMsgMetadata(_fbb, _o->__metadata.get(), _rehasher) : 0;
  return fb::CreateMsgWithMetadata(
      _fbb,
      ___metadata);
}

namespace std_msgs {

inline HeaderT *Header::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::std_msgs::HeaderT> _o = std::unique_ptr<fb::std_msgs::HeaderT>(new HeaderT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Header::UnPackTo(HeaderT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = __metadata(); if (_e) _o->__metadata = std::unique_ptr<fb::MsgMetadataT>(_e->UnPack(_resolver)); }
  { auto _e = seq(); _o->seq = _e; }
  { auto _e = stamp(); if (_e) _o->stamp = std::unique_ptr<fb::RosTime>(new fb::RosTime(*_e)); }
  { auto _e = frame_id(); if (_e) _o->frame_id = _e->str(); }
}

inline flatbuffers::Offset<Header> Header::Pack(flatbuffers::FlatBufferBuilder &_fbb, const HeaderT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateHeader(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Header> CreateHeader(flatbuffers::FlatBufferBuilder &_fbb, const HeaderT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const HeaderT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto ___metadata = _o->__metadata ? CreateMsgMetadata(_fbb, _o->__metadata.get(), _rehasher) : 0;
  auto _seq = _o->seq;
  auto _stamp = _o->stamp ? _o->stamp.get() : 0;
  auto _frame_id = _o->frame_id.empty() ? 0 : _fbb.CreateString(_o->frame_id);
  return fb::std_msgs::CreateHeader(
      _fbb,
      ___metadata,
      _seq,
      _stamp,
      _frame_id);
}

}  // namespace std_msgs

namespace sensor_msgs {

inline NavSatStatusConstantsT *NavSatStatusConstants::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::sensor_msgs::NavSatStatusConstantsT> _o = std::unique_ptr<fb::sensor_msgs::NavSatStatusConstantsT>(new NavSatStatusConstantsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NavSatStatusConstants::UnPackTo(NavSatStatusConstantsT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = status_no_fix(); _o->status_no_fix = _e; }
  { auto _e = status_fix(); _o->status_fix = _e; }
  { auto _e = status_sbas_fix(); _o->status_sbas_fix = _e; }
  { auto _e = status_gbas_fix(); _o->status_gbas_fix = _e; }
  { auto _e = service_gps(); _o->service_gps = _e; }
  { auto _e = service_glonass(); _o->service_glonass = _e; }
  { auto _e = service_compass(); _o->service_compass = _e; }
  { auto _e = service_galileo(); _o->service_galileo = _e; }
}

inline flatbuffers::Offset<NavSatStatusConstants> NavSatStatusConstants::Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusConstantsT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateNavSatStatusConstants(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<NavSatStatusConstants> CreateNavSatStatusConstants(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusConstantsT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const NavSatStatusConstantsT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _status_no_fix = _o->status_no_fix;
  auto _status_fix = _o->status_fix;
  auto _status_sbas_fix = _o->status_sbas_fix;
  auto _status_gbas_fix = _o->status_gbas_fix;
  auto _service_gps = _o->service_gps;
  auto _service_glonass = _o->service_glonass;
  auto _service_compass = _o->service_compass;
  auto _service_galileo = _o->service_galileo;
  return fb::sensor_msgs::CreateNavSatStatusConstants(
      _fbb,
      _status_no_fix,
      _status_fix,
      _status_sbas_fix,
      _status_gbas_fix,
      _service_gps,
      _service_glonass,
      _service_compass,
      _service_galileo);
}

inline NavSatStatusT *NavSatStatus::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::sensor_msgs::NavSatStatusT> _o = std::unique_ptr<fb::sensor_msgs::NavSatStatusT>(new NavSatStatusT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NavSatStatus::UnPackTo(NavSatStatusT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = __metadata(); if (_e) _o->__metadata = std::unique_ptr<fb::MsgMetadataT>(_e->UnPack(_resolver)); }
  { auto _e = status(); _o->status = _e; }
  { auto _e = service(); _o->service = _e; }
}

inline flatbuffers::Offset<NavSatStatus> NavSatStatus::Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateNavSatStatus(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<NavSatStatus> CreateNavSatStatus(flatbuffers::FlatBufferBuilder &_fbb, const NavSatStatusT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const NavSatStatusT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto ___metadata = _o->__metadata ? CreateMsgMetadata(_fbb, _o->__metadata.get(), _rehasher) : 0;
  auto _status = _o->status;
  auto _service = _o->service;
  return fb::sensor_msgs::CreateNavSatStatus(
      _fbb,
      ___metadata,
      _status,
      _service);
}

inline NavSatFixConstantsT *NavSatFixConstants::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::sensor_msgs::NavSatFixConstantsT> _o = std::unique_ptr<fb::sensor_msgs::NavSatFixConstantsT>(new NavSatFixConstantsT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NavSatFixConstants::UnPackTo(NavSatFixConstantsT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = covariance_type_unknown(); _o->covariance_type_unknown = _e; }
  { auto _e = covariance_type_approximated(); _o->covariance_type_approximated = _e; }
  { auto _e = covariance_type_diagonal_known(); _o->covariance_type_diagonal_known = _e; }
  { auto _e = covariance_type_known(); _o->covariance_type_known = _e; }
}

inline flatbuffers::Offset<NavSatFixConstants> NavSatFixConstants::Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixConstantsT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateNavSatFixConstants(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<NavSatFixConstants> CreateNavSatFixConstants(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixConstantsT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const NavSatFixConstantsT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _covariance_type_unknown = _o->covariance_type_unknown;
  auto _covariance_type_approximated = _o->covariance_type_approximated;
  auto _covariance_type_diagonal_known = _o->covariance_type_diagonal_known;
  auto _covariance_type_known = _o->covariance_type_known;
  return fb::sensor_msgs::CreateNavSatFixConstants(
      _fbb,
      _covariance_type_unknown,
      _covariance_type_approximated,
      _covariance_type_diagonal_known,
      _covariance_type_known);
}

inline NavSatFixT *NavSatFix::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<fb::sensor_msgs::NavSatFixT> _o = std::unique_ptr<fb::sensor_msgs::NavSatFixT>(new NavSatFixT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NavSatFix::UnPackTo(NavSatFixT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = __metadata(); if (_e) _o->__metadata = std::unique_ptr<fb::MsgMetadataT>(_e->UnPack(_resolver)); }
  { auto _e = header(); if (_e) _o->header = std::unique_ptr<fb::std_msgs::HeaderT>(_e->UnPack(_resolver)); }
  { auto _e = status(); if (_e) _o->status = std::unique_ptr<fb::sensor_msgs::NavSatStatusT>(_e->UnPack(_resolver)); }
  { auto _e = latitude(); _o->latitude = _e; }
  { auto _e = longitude(); _o->longitude = _e; }
  { auto _e = altitude(); _o->altitude = _e; }
  { auto _e = position_covariance(); if (_e) { _o->position_covariance.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->position_covariance[_i] = _e->Get(_i); } } }
  { auto _e = position_covariance_type(); _o->position_covariance_type = _e; }
}

inline flatbuffers::Offset<NavSatFix> NavSatFix::Pack(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateNavSatFix(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<NavSatFix> CreateNavSatFix(flatbuffers::FlatBufferBuilder &_fbb, const NavSatFixT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const NavSatFixT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto ___metadata = _o->__metadata ? CreateMsgMetadata(_fbb, _o->__metadata.get(), _rehasher) : 0;
  auto _header = _o->header ? CreateHeader(_fbb, _o->header.get(), _rehasher) : 0;
  auto _status = _o->status ? CreateNavSatStatus(_fbb, _o->status.get(), _rehasher) : 0;
  auto _latitude = _o->latitude;
  auto _longitude = _o->longitude;
  auto _altitude = _o->altitude;
  auto _position_covariance = _o->position_covariance.size() ? _fbb.CreateVector(_o->position_covariance) : 0;
  auto _position_covariance_type = _o->position_covariance_type;
  return fb::sensor_msgs::CreateNavSatFix(
      _fbb,
      ___metadata,
      _header,
      _status,
      _latitude,
      _longitude,
      _altitude,
      _position_covariance,
      _position_covariance_type);
}

}  // namespace sensor_msgs
}  // namespace fb

#endif  // FLATBUFFERS_GENERATED_SCHEMA_FB_SENSOR_MSGS_H_
